version: '3.7'

services:
  rabbitmq-dev:
    image: rabbitmq:3.11-management-alpine
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: pass

  api: &api
    image: custom-service_api
    ports:
      - 3000
      - 9090
      - 9229
    build:
      context: .
      target: dev_builder
      dockerfile: docker/Dockerfile
      args:
        NODE_ENV: "development"
    environment: &api_env
      SERVICE_NAME: "custom-service"
      NODE_ENV: "development"
      OPENAPI_URL: "_oa"
      AWS_ACCESS_KEY_ID: "AKUOAUKTZJ3WVGMWJFV7A"
      AWS_SECRET_ACCESS_KEY: "/5FzJ1f8acTZZHhNoFfdEVrqSp4/xBUyIbzSUDla1"
      AWS_DEFAULT_REGION: "eu-central-1"
    stop_grace_period: 60s

  stan-consumer:
    <<: *api
    depends_on:
      - stan-producer
    volumes:
      - ./src:/usr/src/app/src
      - ./stan-output:/usr/src/app/outputs
    environment:
      <<: *api_env
      WORKER_START: 'stan-consumer'
    command: 'npm run start:dev'

volumes:
  custom-service-pg:
